#!/bin/sh
# Modified by Caroline Simpson, 2026-10-05: embed ccv-style.css in HTML.
# Modified by Caroline Simpson, 2026-10-05: add optional --clean pipeline.
# Copyright (C) 2026 Caroline Simpson (modifications).
# SPDX-License-Identifier: GPL-2.0-or-later; see COPYING.

BASEDIR=`dirname "$0"`

if test ! -r "$BASEDIR/ccv-style.css"; then
  echo "Cannot read stylesheet: $BASEDIR/ccv-style.css" >&2
  exit 1
fi

CSS=$(cat "$BASEDIR/ccv-style.css")

CLEAN=no

pipeline() {
  xsltproc "$BASEDIR"/wrap.xslt - | xsltproc --stringparam clean "$CLEAN" "$BASEDIR"/clean.xslt - | xsltproc "$BASEDIR"/ccv2document.xslt - | xsltproc --stringparam clean "$CLEAN" "$BASEDIR"/clean.xslt - | xsltproc "$BASEDIR"/lists.xslt - | xsltproc --stringparam css "$CSS" "$BASEDIR"/markup-html.xslt -
}

usage() {
  echo "ccv2html: convert Canadian Common CV to HTML"
  echo ""
  echo "Usage: ccv2html [options] [infile [outfile]]"
  echo "Options:"
  echo "  -h, --help:   view usage info and quit"
  echo "  --clean:     omit Personal Information and blank fields; fill Organization"
  echo "               from Other Organization when Organization is blank"
  echo "Arguments:"
  echo "  infile:   file to read XML from"
  echo "  outfile:  file to write HTML to"
  echo ""
  echo "If no filenames are specified, read standard input and write standard output."
  echo "Outfile defaults to infile with '.html' extension"
}

while test "$#" -gt 0; do
  case "$1" in
      --clean )
          CLEAN=yes
          shift
          ;;
      -h|--help )
          usage
          exit 0
          ;;
      -* )
          echo "Option $1 not recognized. Try --help for more info." > /dev/stderr
          exit 1
          ;;
      * )
          break;
          ;;
  esac
done

if test "$#" -eq 0; then
  pipeline
elif test "$#" -eq 1; then
  infile="$1"
  outfile=`basename "$1" .xml`.html
  cat "$infile" | pipeline > "$outfile"
elif test "$#" -eq 2; then
  infile="$1"
  outfile="$2"
  cat "$infile" | pipeline > "$outfile"
else
  echo "Too many arguments. Try --help for more info." > /dev/stderr
  exit 1
fi
